### ISSUE TITLE
Nothing happens after using git clone https://github.com/jaschwer/second-repo

### ISSUE THREAD

**Issue by jaschwer** [janboone/open_source_for_economists#4]
Hey,
for some reason the cloning does not work and I don't find any reason for the problem online. 
I copy the command, change the name and execute the line. But then it does not do anything but waits in the next line for something else to be typed. Did anybody have a similar problem or the solution to that problem?
Jakob

Edit: Problem is solved after re-installing git and restarting my laptop.

**Comment by janboone** [comment]
Hi Jakob,

Great that you managed to use git to ask your question and to solve your problem yourself!

Jan.

**Comment by jaschwer** [comment]
Thanks, I was quite happy, too :)

2016-02-29 8:35 GMT+01:00 jan boone <notifications@github.com>:

**Comment by jaschwer** [comment]
Dear Jan Boone,

I wanted to look up my grades for the first assignment, but somehow my
grade was not in the document.
Daniel Dimitrov had registered me, Carlos Gonzalez and hisself as a group.

Regards
Jakob Schwerter

2016-02-29 8:35 GMT+01:00 jan boone <notifications@github.com>:

**Comment by janboone** [comment]
Hi Jakob,

We will check what went wrong and post a new version of the grade list later today.

Jan.
