### ISSUE TITLE
Question about assignment 1... Really need help

### ISSUE THREAD

**Issue by MJWvandenBerg** [janboone/open_source_for_economists#5]
Dear sir Boone,

I keep getting these errors:
![image](https://cloud.githubusercontent.com/assets/17403857/13459084/8c072f5e-e071-11e5-9da2-a87c5427b1c4.png)

Besides that my CV (and ending result of my assignment) works here perfectly: http://htmlpreview.github.io/?https://github.com/MJWvandenBerg/First-Assignment/blob/gh-pages/index.html

however it does not open when I just visit my page directly.. I have been trying for a few hours to fix this, but I cannot get this solved and the internet does not provide me with an answer either. I have followed all the steps that you used for the second-repo, but it keeps giving me these issues.. Also your page speaks about a "master" branch, which never shows up in my repositories...

Hope you can help me out.

Kind regards,
Marc van den Berg

**Comment by janboone** [comment]
just to be sure: you are getting "warnings", not "errors". 

Indeed, your CV works fine. For some reason, you didn't create a master branch, but you do not need it either.

Is this the web address you are looking for: http://mjwvandenberg.github.io/FirstAssignment/?

**Comment by MJWvandenBerg** [comment]
Dear sir Boone,

Thanks for your response. I have now uploaded my CV with the correct and better looking css file and can indeed find it on the link you provided me. I will now close this topic as my problem is solved. 

Kind regards,
Marc van den Berg
